name: Cache > dependency cache update

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "go.sum"


jobs:
  workflow:
    uses: releaseband/cicd/.github/workflows/golang-cache-dependency-update.yml@main
    secrets: inherit